openapi: '3.0.3'
info:
  title: ContractIA
  description: API para la gestión de contratos, usuarios y chatbot.
  version: '1.0.0'
  license:
    name: Proprietary - All Rights Reserved
    url: https://github.com/NickSalA/ContractIA/blob/main/LICENSE
  contact:
    name: NickSalA
    url: https://github.com/NickSalA/ContractIA
    email: contact@example.com
servers:
  - url: https://api.server.test/v1
tags:
  - name: Autenticación
    description: Operaciones relacionadas con la autenticación de usuarios.
  - name: Usuarios
    description: Operaciones para la gestión de usuarios.
  - name: Chatbot
    description: Operaciones para interactuar con el chatbot.
  - name: Contratos
    description: Operaciones para la gestión de contratos.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /login:
    post:
      summary: Iniciar sesión
      description: Permite a un usuario iniciar sesión proporcionando email y contraseña.
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      tags: 
        - Autenticación

      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  
  /user:
    post:
      summary: Crear un nuevo usuario
      description: Permite crear un nuevo usuario proporcionando email, contraseña y rol.
      operationId: createUser
      tags: 
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Bad Request

  /user/{id}:
    get:
      summary: Obtener un usuario existente
      operationId: getUser
      description: Retrieves a specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags: 
        - Usuarios
      responses:
        '200':
          description: OK
    delete:
      summary: Eliminar un usuario existente
      operationId: deleteUser
      description: Deletes a specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags: 
        - Usuarios
      responses:
        '204':
          description: No Content
    patch:
      summary: Actualizar un usuario existente
      operationId: updateUser
      description: Updates a specific user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: email
          in: query
          required: false
          schema:
            type: string
        - name: password
          in: query
          required: false
          schema:
            type: string
      tags: 
        - Usuarios
      responses:
        '200':
          description: OK
  
  /chat:
    post:
      summary: Enviar un mensaje al chatbot
      operationId: sendMessage
      tags: 
        - Chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                thread_id:
                  type: string
      responses:
        '200':
          description: OK

  /contract:
    post:
      summary: Subir un nuevo contrato
      operationId: createContract
      tags: 
        - Contratos
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Contrato creado
    get:
      summary: Obtener todos los contratos existentes
      operationId: getAllContracts
      description: Retrieves all existing contracts
      tags: 
        - Contratos
      responses:
        '200':
          description: OK
  /contract/{id}:
    get:
      summary: Obtener un contrato existente
      operationId: getContract
      description: Retrieves a specific contract by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags: 
        - Contratos
      responses:
        '200':
          description: OK
    delete:
      summary: Eliminar un contrato existente
      operationId: deleteContract
      description: Deletes a specific contract by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags: 
        - Contratos
      responses:
        '204':
          description: No Content
  
  /conversation/{id}:
    get:
      summary: Obtener el historial de una conversación
      operationId: getConversationHistory
      description: Retrieves the history of a specific conversation by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags: 
        - Chatbot
      responses:
        '200':
          description: OK