openapi: '3.0.3'
info:
  title: ContractIA
  version: '1.0.0'
servers:
  - url: https://api.server.test/v1
paths:
  /user:
    post:
      summary: Crear un nuevo usuario
      operationId: createUser
      tags: 
        - Usuarios
      responses:
        '201':
          description: Usuario creado
    get:
      summary: Obtener un usuario existente
      operationId: getUser
      responses:
        '200':
          description: OK
