components:
  schemas:
    DocumentType:
      type: string
      enum: [SERVICIOS, LICENCIAS, SOPORTE]
      description: El tipo de documento (e.g., servicios, licencias).
      example: SERVICIOS

    DocumentState:
      type: string
      enum: [ACTIVO, POR_VENCER, EXPIRADO]
      description: El estado actual del documento (e.g., activo, expirado).
      example: ACTIVO

DocumentCreateRequest:
  type: object
  properties:
    file:
      type: string
      format: binary
    name:
      type: string
      description: El nombre del documento.
      example: Plataforma Corporativa Pro
    client:
      type: string
      description: El nombre del cliente asociado al documento.
      example: Acme Corp
    type:
      $ref: '#/components/schemas/DocumentType'
    start_date:
      type: string
      format: date
      description: La fecha de inicio del contrato o documento.
      example: 2024-01-01
    end_date:
      type: string
      format: date
      description: La fecha de finalización del contrato o documento.
      example: 2024-12-31
    value:
      type: number
      format: float
      description: El valor monetario asociado al documento.
      example: 10000.00
    licenses:
      type: integer
      description: El número de licencias asociadas al documento.
      example: 5
  required:
    - file
    - name
    - client
    - type
    - start_date
    - end_date
    - value
    - licenses

DocumentResponse:
  type: object
  properties:
    id:
      type: integer
      description: El identificador único del documento.
      example: 1
    name:
      type: string
      description: El nombre del documento.
      example: Plataforma Corporativa Pro
    client:
      type: string
      description: El nombre del cliente asociado al documento.
      example: Acme Corp
    type:
      $ref: '#/components/schemas/DocumentType'
    start_date:
      type: string
      format: date
      description: La fecha de inicio del contrato o documento.
      example: 2024-01-01
    end_date:
      type: string
      format: date
      description: La fecha de finalización del contrato o documento.
      example: 2024-12-31
    value:
      type: number
      format: float
      description: El valor monetario asociado al documento.
      example: 10000.00
    licenses:
      type: integer
      description: El número de licencias asociadas al documento.
      example: 5
    state:
      $ref: '#/components/schemas/DocumentState'
    # filename:
    #   type: string
    #   description: El nombre del archivo subido.
    #   example: contrato.pdf
    # size:
    #   type: integer
    #   description: El tamaño del archivo en bytes.
    #   example: 204800
  required:
    - id
    - name
    - client
    - type
    - start_date
    - end_date
    - value
    - licenses
    - state

DocumentListResponse:
  type: array
  items:
    type: object
    properties:
      id:
        type: integer
        description: El identificador único del documento.
        example: 1
      name:
        type: string
        description: El nombre del documento.
        example: Plataforma Corporativa Pro
      client:
        type: string
        description: El nombre del cliente asociado al documento.
        example: Acme Corp
      type:
        $ref: '#/components/schemas/DocumentType'
      start_date:
        type: string
        format: date
        description: La fecha de inicio del contrato o documento.
        example: 2024-01-01
      end_date:
        type: string
        format: date
        description: La fecha de finalización del contrato o documento.
        example: 2024-12-31
      value:
        type: number
        format: float
        description: El valor monetario asociado al documento.
        example: 10000.00
      licenses:
        type: integer
        description: El número de licencias asociadas al documento.
        example: 5
      state:
        $ref: '#/components/schemas/DocumentState'
      # filename:
      #   type: string
      #   description: El nombre del archivo subido.
      #   example: contrato.pdf
      # size:
      #   type: integer
      #   description: El tamaño del archivo en bytes.
      #   example: 204800
    required:
      - id
      - name
      - client
      - type
      - start_date
      - end_date
      - value
      - licenses
      - state
