ChatRequest:
  type: object
  required:
    - message
  properties:
    message:
      type: string
      description: The user's message to the chatbot.
      example: "Hola, ¿cómo estás?"
    thread_id:
      type: integer
      description: ID de la conversación.
      example: 12

ChatResponse:
  type: object
  required:
    - response
    - thread_id
  properties:
    response:
      type: string
      description: The chatbot's response to the user's message.
      example: "¡Hola! Estoy bien, gracias por preguntar. ¿En qué puedo ayudarte hoy?"
    thread_id:
      type: integer
      description: ID de la conversación.
      example: 12
